### ISSUE TITLE
addon should be recording 'dwell time' for all urls for duration of the study

### ISSUE THREAD

**Issue by lonnen** [mozilla/pioneer-study-online-news#1]
The addon should record dwell time per url for the duration of the study where dwell time is the number of minutes where a user has interacted with the page (a user generated event occurs) or the full screen api is engaged. 

This may be impractical, and if we must we could fall back to tld+1 instead of url

**Comment by lonnen** [comment]
prior art: https://www.microsoft.com/en-us/research/wp-content/uploads/2010/10/SIGIR2010-DwellTimeModel.pdf

Dwell time was implemented as a session based log, where user activity started the log, page visit times are recorded until either the browser is closed or 30-min of inactivity.

I had imagined a matrix with tld+1 rows and columns per minute, sort of a statsd approach. The matrix would be sparse for most users. We could compact it but it gets complex. With only light modification this log-like approach may be a better way of recording and transmitting our data. We can post process the output to yield an easier to analyze data structure.

**Comment by Osmose** [comment]
I implemented this per-domain (with subdomains being separate entries) after my first skim, but that can be changed to per-URL trivially. 

More questions for @rjweiss:

1. Do we want per-URL, or per-domain counts?
2. How precise do we want to measure the time when viewing occurred? Currently the implementation is just counting the number of milliseconds active, with the assumption that we'd batch the counts into 30 minute chunks. Would that work for our purposes?
3. We can set a delay (in seconds) for how long after the user's last activity we consider them idle. What do we want that to be set to?

**Comment by lonnen** [comment]
some answers:

1. url, probably. For pioneer studies we can err on the side of more granular and then reduce resolution downstream.
2. What are the trade offs for adding resolution here? I'm not sure that anything below 1 second is useful, but see above (1). In general we'd like to minimize the perf impact of the intervention.
3. In earlier discussions we've talked about 5 minutes as the right window

**Comment by Osmose** [comment]
> some answers:
> 
> 1. url, probably. For pioneer studies we can err on the side of more granular and then reduce resolution downstream.

CC @mythmon since this means changes to #11

> 2. What are the trade offs for adding resolution here? I'm not sure that anything below 1 second is useful, but see above (1). In general we'd like to minimize the perf impact of the intervention.

Perf-wise, my reading of the [nsIIdleService docs](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIIdleService) suggests that Firefox is already pinging the OS-level idle detection every 5 seconds, and our delay doesn't really affect that. Measuring milliseconds vs seconds doesn't really have a perf impact, so maybe we should just stick with milliseconds and reduce resolution like you mentioned.
