### ISSUE TITLE
need copy explaining the alignment score for the "learn more" page 

### ISSUE THREAD

**Issue by rjweiss** [mozilla/pioneer-study-online-news#10]
The user notification bar should present a link on the far right saying "more info". That link should open a new tab with a self hosted documentation page containing the doc contents. (edit lonnen)

**Comment by rjweiss** [comment]
@SolomonMg provided it here: https://docs.google.com/document/d/1333rioVLAzt3wnvubjMQRNhn5z6FgSjrtiWcmcvqWbE/edit 

(edit mythmon). The content of the document is:

> This rating is based on a measure of “ideological alignment” from an academic study - [Bakshy, Messing, and Adamic (2015)](http://science.sciencemag.org/content/348/6239/1130).  This measure averages the self-reported ideology (where -2 is very liberal and 2 is very conservative) of users who shared an article from this source on a major social media website. “Alignment” is not a measure of media slant; rather, it captures differences in the kind of content shared among a set of partisans, which can include topic matter, framing, and slant.
>
> Bakshy E., Messing S., Adamic L. (2015). Exposure to ideologically diverse news and opinion on Facebook. Science, 348, 1130–1132. doi:10.1126/science.aaa1160

**Comment by lonnen** [comment]
We'll set up a link that says "more info" in the notification. That more info link should:

a. link directly to the paper in the blurb
b. open a new tab with a self hosted documentation page containing the doc contents
c. something else

@rjweiss ^ ?

**Comment by lonnen** [comment]
unless otherwise directed, b

**Comment by rjweiss** [comment]
B is right to me.

**Comment by rehandalal** [comment]
our plan is to open up something along the lines of `resource://pioneer-study-online-news/content/learn-more.html` in a new tab. where that URL points to some HTML file that ships with the addon. is that okay?

it's not the prettiest URL but i assume that's fine?

**Comment by lonnen** [comment]
wfm

**Comment by rehandalal** [comment]
![learn-more](https://user-images.githubusercontent.com/987136/31907080-c4d6f036-b800-11e7-94a9-db32ac5e6398.png)

**Comment by lonnen** [comment]
wfm
