### ISSUE TITLE
Verify that the domains.json file only contains TLD+1 hostnames

### ISSUE THREAD

**Issue by crankycoder** [mozilla/pioneer-study-online-news#14]
We filter the tracking based on the domains.json file - need to double check that we are capturing enough of the hostname when doing the set containment match.

**Comment by crankycoder** [comment]
This isn't actually the case. 

The `domains.json` file seems to have hosts that won't show up properly.

For example - 'battleforthenet.com' shows up in domains.json, but the actual host 'battleforthenet.com' will redirect to 'www.battleforthenet.com'.

I don't think we want to filter out the www prefix automatically, but doing nothing seems to also be wrong as sites like battleforthenet will never show up.

The `domains.json` dataset contains sub-domains where the rankings are slightly different like - which seems to indicate we *don't* want to normalize the domains automatically. 

```
    {
        "avgAlign": 0.0634,
        "domain": "www.youtube.com",
        "l1": 0.2184,
        "l2": 0.1533,
        "n": 0.1947,
        "r1": 0.2606,
        "r2": 0.173
    },
```
and
```
    {
        "avgAlign": 0.105,
        "domain": "m.youtube.com",
        "l1": 0.3193,
        "l2": 0.1045,
        "n": 0.1477,
        "r1": 0.2203,
        "r2": 0.2082
    },
```

Not sure what to do here.  I'm leaning towards just trusting the domains.json data and if we never get a match like in the case of battleforthenet.com - well - tough luck.  @lonnen ?

**Comment by lonnen** [comment]
1. do nothing
2. use a cannonizer function?
3. I'll bring it up tomorrow AM at the research meeting, don't wait for it.

**Comment by rehandalal** [comment]
spoke to @vng who said "this is useless"
