### ISSUE TITLE
Persist all the dwell time as parquet data

### ISSUE THREAD

**Issue by crankycoder** [mozilla/pioneer-study-online-news#15]
We need to persist the dwell time as a log in a parquet file.

Roughly this means we need to capture the load time, the start of a dwell and the end of a dwell on a per URL basis.

I'm leaning towards just writing the files to the user profile directory in a dedicated subdirectory.  Write to a temporary log file first, then move to the dedicated directory with a time stamped filename.

We need a parquet schema, some samples for documentation purposes and code that hooks the File.jsm module to write everything to disk.

**Comment by mythmon** [comment]
My experience with Shield and other studies has taught me that the correct place to store this data is IndexedDB. It manages error handling, data persistence, and durability well for us. Here is an example of a study that uses IndexedDB for data storage: https://github.com/mozilla/share-button-study/blob/master/extension/PingStorage.jsm

Also, to be clear, are you saying we should generate Parquet files on the client? Or are we going to use the normal Pioneer data pipeline (via Telemetry) to send JSON that then gets converted into Parquet?

**Comment by crankycoder** [comment]
Sorry - I just meant to store files in JSON format that get converted into Parquet to use the regular telemetry pipeline.    Thx for the link - indexeddb storage it is then.
