### ISSUE TITLE
Need an metrics.md documenting what data is collected and how

### ISSUE THREAD

**Issue by rjweiss** [mozilla/pioneer-study-online-news#16]

**Comment by rehandalal** [comment]
oops sorry, accidentally hit close.

**Comment by rehandalal** [comment]
is this just for the repo? or are we distributing this with the addon?

**Comment by rjweiss** [comment]
Just for the repo.

**Comment by lonnen** [comment]
@rjweiss not sure what this file is or requires. can you add example, detail, or docs?

**Comment by rjweiss** [comment]
This does not block QA.  A metrics.md doc is a file that summarizes what is being measured, why, and what a measurement artifact looks like (e.g. the ping json, Google Analytics schema, etc).  

See screenshots' example: https://github.com/mozilla-services/screenshots/blob/master/docs/METRICS.md

I suspect you are all already doing something similar, it's more a matter of following similar conventions.
