### ISSUE TITLE
Need IRB details for "needs more info" page

### ISSUE THREAD

**Issue by rjweiss** [mozilla/pioneer-study-online-news#17]
Additionally, the debrief information included in the IRB should go into the final survey.

**Comment by ylelkes** [comment]
IRB debrief to be embedded  in final survey
[IRB-SBS Sample Debriefing Template.docx](https://github.com/mozilla/pioneer-study-online-news/files/1447168/IRB-SBS.Sample.Debriefing.Template.docx)

**Comment by reiclan** [comment]
xcvxv

**Comment by reiclan** [comment]
v

**Comment by reiclan** [comment]
4wes f

**Comment by rjweiss** [comment]
IRB information is now included in the surveys
