### ISSUE TITLE
Format of the browsing logs

### ISSUE THREAD

**Issue by rehandalal** [mozilla/pioneer-study-online-news#23]
This is currently the way that we are creating log entries:

The user focuses on a URL (either by navigating to it or focusing the window/tab that it is loaded in):
```json
{"details": "focus-start", "timestamp": 12341234, "url": "http://some-url.com/something.html"}
``` 

The user is idle for more than 5 seconds:
```json
{"details": "idle-start", "timestamp": 12341234, "url": "http://some-url.com/something.html"}
``` 

The user stops idling:
```json
{"details": "idle-end", "timestamp": 12341234, "url": "http://some-url.com/something.html"}
``` 

The user navigates away from a URL or unfocuses the window/tab:
```json
{"details": "focus-end", "timestamp": 12341234, "url": "http://some-url.com/something.html"}
``` 

Does this seem okay?

**Comment by rjweiss** [comment]
This is good to me.  This does not include measurements for the intervention (i.e. recording the participants agreement or disagreement with the alignment score for a specific URL).  Will that come later?  Is that going to be another field in a similar log format?

**Comment by rehandalal** [comment]
I didn't include that here but this is what the log would include for those:

Agree with rating:
```json
{"details": "agree", "timestamp": 12341234, "url": "www.website.com"}
```

Disagree with rating:
```json
{"details": "disagree", "timestamp": 12341234, "url": "www.website.com"}
```

Dismiss doorhanger without selecting rating:
```json
{"details": "dismiss", "timestamp": 12341234, "url": "www.website.com"}
```
