### ISSUE TITLE
Survey doorhanger content

### ISSUE THREAD

**Issue by rehandalal** [mozilla/pioneer-study-online-news#24]
As per https://github.com/mozilla/pioneer-study-online-news/issues/12 it sounds like we want to have a doorhanger for prompting users to take the survey.

What should go in this doorhanger?

I assume:
- some text explaining what/why the survey
- a button to open the survey

**Comment by rehandalal** [comment]
For a sample of what the existing doorhanger for alignment ratings look like, see here:
https://github.com/mozilla/pioneer-study-online-news/issues/3#issuecomment-342291653

**Comment by rjweiss** [comment]
IMO, we should keep this text simple and relatively standardized across all Pioneer studies for now.  E.g.:

"Thank you for being a Firefox Pioneer!  We have some additional questions we'd like to ask you."

And then a button that says "Take a survey" 

@lonnen feedback on this proposal?

**Comment by lonnen** [comment]
that sounds fine to me

**Comment by rjweiss** [comment]
@rehandalal this issue is now related to #42
