### ISSUE TITLE
page intervention script should show the user some info

### ISSUE THREAD

**Issue by lonnen** [mozilla/pioneer-study-online-news#3]
based on the treatment, the intervention script should recognize and display a door hanger to the user with some information about the page based on eTLD+1

kind of like CFR

**Comment by lonnen** [comment]
*edit: SVG is an option. We probably want that instead of ASCII*

notes from a discussion:

In our [canonical list of eTLDs](https://docs.google.com/spreadsheets/d/1LHarYKcgcRkHfRlVar6UFAt0dRiV2togo7NNeiAvLTQ/edit?ts=599640a0#gid=82080898) to examine, we have a avg_align column with values ranging from (-1, 1). We'd like to indicate this domain to the user visually. If we only have text available, partitioning out the domain into 5 even buckets and using ascii is ok.

```
(   ) -> |-----|
( -1) -> |X----|
(0.5) -> |---X-|
(0.1) -> |--X--|
```

If we have more sophisticated methods, say a simple SVG bar or [bullet chart](http://www.d3noob.org/2013/07/introduction-to-bullet-charts-in-d3js.html) is more useful.

**Comment by mythmon** [comment]
As a note, the UI will not be limited to text only, but something like d3 is probably out of scope. SVGs sound like the right balance if we can get some assets for it.

**Comment by lonnen** [comment]
@rjweiss -- what is the copy we should use in the infobar?

```
specific text  <svg showing 0-1>
```

**Comment by lonnen** [comment]
"I'll update the issue when I [hear back from collaborators]" - @rjweiss

**Comment by lonnen** [comment]
until we hear back, use some judgement-less dummy text like "This site is placed here on the scale of alignment scoring." and then a pair of svgs indicating a bar chart

**Comment by lonnen** [comment]
Now that I think about it a simple bar chart is probably wrong. We want to avoid color, since that has cultural connotations. We want to indicate something similar to the ascii art above.

**Comment by rjweiss** [comment]
I vote for a black horizontal line with a point, similar to the ASCII art.

Conferred with @ylelkes and @SolomonMg, let's use the following copy:
> Based on a recent paper published in Science, the social media ideological alignment of this site is:

And if the SVG can look something like this:
> More liberal    [ …|..........]   More conservative

where "more liberal" is anchored at the -1 endpoint and "more conservative" is anchored at the 1 endpoint.

**Comment by rjweiss** [comment]
@mythmon I observe that we are missing a detail from this spec.  There should be three buttons on the doorhanger with the doorhanger.  

- Agree
- Disagree
- Dismiss

And the copy should then say:

> Based on a recent paper published in Science, the social media ideological alignment of this site is:
> More liberal [ …|..........] More conservative
> Do you agree or disagree? [Agree/Disagree/Dismiss]

Feasible or not?

**Comment by mythmon** [comment]
I would propose a door hanger design for the buttons, similar to the screenshot in #12. It would have two buttons, Agree and Disagree, and it would implicitly dismiss in the ways that door hangers usually do. It could also have an explicit close X in the corner.

**Comment by rjweiss** [comment]
Having two buttons and an explicit X close sounds good to me.

**Comment by rehandalal** [comment]
how often would we show this doorhanger? would it just be once per domain per day? once per day, period? something else entirely?

**Comment by lonnen** [comment]
Once per day per domain seems right

**Comment by rehandalal** [comment]
Doorhanger for reuters.com (avgAlign rounds to 0 so bar is empty):
<img width="409" alt="screen shot 2017-11-06 at 4 21 35 pm" src="https://user-images.githubusercontent.com/987136/32464685-df643c88-c30e-11e7-87de-1fbcad2f503b.png">

Doorhanger for rollingstone.com:
<img width="407" alt="screen shot 2017-11-06 at 4 21 56 pm" src="https://user-images.githubusercontent.com/987136/32464690-e3fee5ae-c30e-11e7-81c2-ef78bcfdc44a.png">

**Comment by lonnen** [comment]
per meeting discussing:

the case of 0 is odd. we should either:

1. remove the line in the center and replace it with a square for an odd number of squares
2. highlight the squares on either side of the middle line

do the second one

**Comment by lonnen** [comment]
for posterity, I prefer 2 over 1 because removing the axis marking center leaves only variable length labels as the framing. In the case of a 0, then, it is unclear if that single square _is_ the center or if that indicates a position on a slider. Much slower to parse.

**Comment by rehandalal** [comment]
@lonnen 2 has already been implemented and is in #27

**Comment by ylelkes** [comment]
would it be possible to strike "social media" from "Based on a recent paper published in Science, the  ideological alignment of this site"

**Comment by mythmon** [comment]
@ylelkes that has been done in #40.
