### ISSUE TITLE
addon put users in one of two treatments during week 4, 5, 6

### ISSUE THREAD

**Issue by lonnen** [mozilla/pioneer-study-online-news#4]
The page intervention script should implement three treatments:

0. no action
1. looks for eTLD+1 in a list of 500 sites and displays a message based on thresholds in the 'score' function. Exact messaging TBD in another issue, for now we can just display the score.
2. ~~derive a similar treatment from the metacert api, if possible~~

Each intervention should present as a door hanger and prompt for agree/disagree from the user, and a more information link (tbd in a different issue). Addon should record which site, that a door hanger was shown, and which interaction, if any, the user took with the door hanger. Addon must not intervene more than once per day on any one particular eTLD+1.

**Comment by rjweiss** [comment]
csv of 500 sites is here: https://docs.google.com/spreadsheets/d/1LHarYKcgcRkHfRlVar6UFAt0dRiV2togo7NNeiAvLTQ/edit?ts=599640a0#gid=82080898

Message should current show the value in avg_align column.

**Comment by lonnen** [comment]
edit: an earlier design called for a metacert-based treatment. we've since dropped that, and reduced to two treatments (control, 500 sites csv)

**Comment by lonnen** [comment]
lgtm
