### ISSUE TITLE
need to associate individual Pioneer clients with their individual survey response

### ISSUE THREAD

**Issue by rjweiss** [mozilla/pioneer-study-online-news#42]
A unique ID associated with the Pioneer client needs to be sent as a URL parameter to the survey link.

It appears that shield utils provides a `surveyURL` object that includes relevant information, but since I signed off on not using shield utils in #8 , we will need to include that information ourselves.

In SurveyGizmo, we can embed a variable in the survey response that can contain the value of the unique ID (example of how this is configured in the SurveyGizmo interface below)

![image](https://user-images.githubusercontent.com/903753/32917807-2d9b44d2-cad5-11e7-9baa-88fe3ee39f51.png)

**Comment by rehandalal** [comment]
We are already passing through this unique id as `pioneer_id` as per: 
https://github.com/mozilla/pioneer-study-online-news/blob/master/extension/lib/Phases.jsm#L134

**Comment by rehandalal** [comment]
The URL for surveys should look like:
`{survey_url}?utm_source=pioneer&utm_campaign=online-news&pioneer_id={unique_id}`

**Comment by rjweiss** [comment]
Let me confirm that I can embed this easily in the survey and then we should be ok to close this.

**Comment by raymak** [comment]
@rjweiss, you can create a hidden variable with [url("pioneer_id")] in it. It will automatically capture the url variable from the survey link.

@rehandalal what is the doorhanger survey? https://github.com/mozilla/pioneer-study-online-news/blob/master/extension/lib/SurveyDoorhanger.jsm#L68  I am not familiar with the study or the code and just stumbled upon this on my first attempt to find where the survey is being opened.

**Comment by rehandalal** [comment]
That is the door hanger that contains the button used to launch these surveys.

**Comment by rjweiss** [comment]
Thanks @raymak!   That satisfies my need for opening this issue.

For the sake of this issue, we can close this issue whenever (I see there is another question here for @rehandalal but it's not a blocker.
