### ISSUE TITLE
survey door hanger shows 3 times even if users click through

### ISSUE THREAD

**Issue by lonnen** [mozilla/pioneer-study-online-news#48]
The 'take a survey' door hanger will always show three times, even if a user clicks through to the survey. We have no means of knowing if a user has completed it, but for some % of users they may complete it more than once or suffer survey fatigue that will distort the survey.

We need options for fixing this.

**Comment by rehandalal** [comment]
I have a PR open with a patch for this addon, if there is a good way to swap out the study addon that might be the best option.

Alternatively I was thinking about this problem and another solution might just be to write a second addon and ship that to the same population. The second addon can watch to see if the user navigates to one of the survey URLs and if that happens we can update the state pref. I suspect this might be the cleanest and most reliable solution.

**Comment by rehandalal** [comment]
I wrote an addon that should do what we want:
https://github.com/rehandalal/pioneer-online-news-survey-fix
