### ISSUE TITLE
addon should prompt users with surveys

### ISSUE THREAD

**Issue by lonnen** [mozilla/pioneer-study-online-news#6]
we need to show four total surveys. this may be part of the study, or pop under with the survey. check with @raymak about the implementation in the net neutrality study

**Comment by lonnen** [comment]
four surveys may be implemented as heartbeats targeted to this addon.

1. at outset
2. before treatment starts
3. after treatment ends
4. at conclusion

**Comment by mythmon** [comment]
Duplicate of #12?
