### ISSUE TITLE
Shield Study Utils Events

### ISSUE THREAD

**Issue by Osmose** [mozilla/pioneer-study-online-news#8]
The [Shield Study Utils](https://github.com/mozilla/shield-studies-addon-utils/) by default sends data via Telemetry about several study events:

- Enrollment
- Installation
- Failing an elligibility test
- Study ends for a variety of reasons (positive, negative, uninstalled)

These events are currently sent via normal telemetry. Modifying the utils to send this data using the Pioneer encrypted channel will take some effort and testing.

@rjweiss Do we need any of this information for this study? If not, then we could save some dev time by avoiding using the study utils completely, as we probably only need a small amount of functionality that we can copy from it or other sources, like stable sampling.

**Comment by Osmose** [comment]
FWIW if only a subset of these events would be necessary, we could implement them manually instead of using the utils.

**Comment by rjweiss** [comment]
Would I not be able to answer the following questions without this data?

- Number of people who have decided to eject themselves from the study
- Total number of enrollments
- Total number of enrollments at date N

**Comment by Osmose** [comment]
> Would I not be able to answer the following questions without this data?
> 
>     Number of people who have decided to eject themselves from the study
>     Total number of enrollments
>     Total number of enrollments at date N

We could answer those with a subset of the measurements, probably just "enroll, unenroll, expired".

If those are the main questions then I think we can skip using the utils.

**Comment by rjweiss** [comment]
I should also add "number of people ejecting themselves from the study at date N."  Then I think we're okay.

**Comment by mythmon** [comment]
My plan is to structure this as timestamped events, similar to how [shield-study-utils]() does events. That means there will be multiple encrypted pings with a format similar to:

```js
{
  "clientId": "1234-5678923-4567890", // or maybe this is somewhere else in the ping?
  "timestamp": "1507754913000", // milliseconds since epoch
  "eventType": "enrolled", // or "ejected", or "study ended", or whatever
}
```

I think this should be able to answer the questions, as long as the correct event types are fired.

**Comment by rehandalal** [comment]
You'll likely need to create an appropriate schema here as well:
https://github.com/mozilla-services/mozilla-pipeline-schemas/tree/master/schemas/pioneer-study
